feat(zh-hk.yml): Added Traditional Chinese language
Sytm/waypoints2 pull request #110
Opened 2024-06-03 10:38 UTC by chunkiuu

Changes: 
Added Traditional Chinese language `zh-hk.yml`

I have ensured all translations are correct, as I am a native speaker of the Traditional Chinese language. :D

2024-06-03 15:21 UTC, Sytm requested changes
Thank your very much for this contribution!

Although there are some tiny issues that should be resolved quickly

2024-06-03 15:21 UTC, Sytm commented on waypoints/src/main/resources/lang/zh-hk.yml
> +#本翻譯是由 ItzTheBear 創建 (Discord: chunkiu) 請聯絡本人如果有任何翻譯錯誤，或您可以自行在Github上進行Pull request。
Please make this header more like the others, although it is fine by me if you add your Discord in there

2024-06-03 15:21 UTC, Sytm commented on waypoints/src/main/resources/lang/zh-hk.yml
> +        # required_balance: Vault balance required for teleportation
The indentation is wrong, these are considered part of the string above

2024-06-03 15:21 UTC, Sytm commented on waypoints/src/main/resources/lang/zh-hk.yml
> +    confirm: "<dark_gray>你確定嗎？"
Trailing space

2024-06-03 15:21 UTC, Sytm commented on waypoints/src/main/resources/lang/zh-hk.yml
> +        owner: "<gray>擁有者: <gold><owner>"
This is supposed to be a child of public, not permission

2024-06-03 15:21 UTC, Sytm commented on waypoints/src/main/resources/lang/zh-hk.yml
> +  # amount: Amount of waypoints in this global folder visible for the player
Empty newline above went missing (I like to keep the spacing between entries across languages identical)

2024-06-03 18:44 UTC, chunkiuu commented
Sorry for having too many errors. The indentation problems should be exactly the same as the `en.yml`.
Let me know if there are more mistakes that need to be fixed :D

2024-06-04 14:04 UTC, Sytm approved these changes

2024-06-04 14:04 UTC, merged